[project]
name = "shooting-game"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aioconsole>=0.8.1",
    "pip>=25.1.1",
    "pydantic>=2.11.4",
    "websockets>=15.0.1",
]
